module.exports = [
  {
    make: 'Audi',
    model: 'RS 7',
    year: 2018,
    price: 113900,
    horsePower: 560,
    fuelType: 'gasoline',
    engineVolume: 4.0,
    engineType: 'V-8',
    driveType: 'All-wheel',
    combinedMpg: 17,
    imageUrl: 'images/audi-rs7.jpeg'
  },
  {
    make: 'Alfa Romero',
    model: '4C Spider',
    year: 2018,
    price: 65900,
    horsePower: 237,
    fuelType: 'gasoline',
    engineVolume: 1.7,
    engineType: 'I-4',
    driveType: 'Rear-wheel',
    combinedMpg: 17,
    imageUrl: 'images/alpha-romero.jpeg'
  },
  {
    make: 'Ford',
    model: 'Shelby GT350',
    year: 2018,
    price: 55845,
    horsePower: 526,
    fuelType: 'gasoline',
    engineVolume: 5.2,
    engineType: 'V-8',
    driveType: 'Rear-wheel',
    combinedMpg: 17,
    imageUrl: 'images/mustang.jpeg'
  },
  {
    make: 'Jaguar',
    model: 'F-TYPE',
    year: 2018,
    price: 59900,
    horsePower: 296,
    fuelType: 'gasoline',
    engineVolume: 2.0,
    engineType: 'I-4',
    driveType: 'Rear-wheel',
    combinedMpg: 18,
    imageUrl: 'images/jaguar.jpeg'
  },
  {
    make: 'Mercedes-Benz',
    model: 'AMG GT',
    year: 2018,
    price: 112400,
    horsePower: 560,
    fuelType: 'gasoline',
    engineVolume: 4.0,
    engineType: 'V-8',
    driveType: 'All-wheel',
    combinedMpg: 18,
    imageUrl: 'images/mercedes.jpeg'
  },
  {
    make: 'Porsche',
    model: '911',
    year: 2018,
    price: 91100,
    horsePower: 370,
    fuelType: 'gasoline',
    engineVolume: 3.0,
    engineType: 'H-6',
    driveType: 'All-wheel',
    combinedMpg: 18,
    imageUrl: 'images/porsche.jpeg'
  },
  {
    make: 'Aston Martin',
    model: 'Vanquish',
    year: 2018,
    price: null,
    horsePower: 568,
    fuelType: 'gasoline',
    engineVolume: 6.0,
    engineType: 'V-12',
    driveType: 'Rear-wheel',
    combinedMpg: 16,
    imageUrl: 'images/aston-martin.png'
  },
  {
    make: 'Audi',
    model: 'R8',
    year: 2018,
    price: null,
    horsePower: 540,
    fuelType: 'gasoline',
    engineVolume: 5.2,
    engineType: 'V-10',
    driveType: 'All-wheel',
    combinedMpg: 17,
    imageUrl: 'images/audi-r8.jpeg'
  },
  {
    make: 'Tesla',
    model: 'Model S',
    year: 2017,
    price: 69000,
    horsePower: null,
    fuelType: 'electric',
    engineVolume: null,
    engineType: 'V-10',
    driveType: 'All-wheel',
    combinedMpg: null,
    imageUrl: 'images/tesla.png'
  },
]